login:
  LOGON_APPLID: "A72CP1AW"
  LOGMODE: "SNX32702"
ccms_path: "C:\\Program Files\\Notepad++\\notepad++.exe"
input_excel_path: "test.xlsx"
output_excel_path: "modified_test.xlsx"
login_page_string: "login"
login_failed_message: "登入失敗，請確認後再執行RPA"
open_exe_delay_after_seconds: "3"
excel_card_number_column_name: "卡號"
processname: "notepad++"
